services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: patchcore_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    volumes:
      # Overlays (persisten fuera del contenedor)
      - ./Backend/static/overlays:/app/Backend/static/overlays
      # Banco de memoria PatchCore (solo lectura)
      - ./Backend/models/patchcore:/app/Backend/models/patchcore:ro
      # (Opcional) editar front en caliente
      - ./Backend/templates:/app/Backend/templates:ro
      - ./Backend/static/assets:/app/Backend/static/assets:ro
      # (Opcional) dataset local en solo lectura
      - ./Dataset:/app/Dataset:ro
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
